require("engine/test/bustedhelper")

local gate_placeholder_class = require("gate_placeholder")

describe('gate_placeholder', function()
  local gate_placeholder

  before_each(function()
    gate_placeholder = gate_placeholder_class()
  end)

  describe("gate type", function()
    describe("type", function()
      it("should return '?'", function()
        assert.are.equals('?', gate_placeholder.type)
      end)
    end)

    describe("is_i", function()
      it("should return false", function()
        assert.is_false(gate_placeholder:is_i())
      end)
    end)

    describe("is_h", function()
      it("should return true", function()
        assert.is_false(gate_placeholder:is_h())
      end)
    end)

    describe("is_x", function()
      it("should return false", function()
        assert.is_false(gate_placeholder:is_x())
      end)
    end)

    describe("is_y", function()
      it("should return false", function()
        assert.is_false(gate_placeholder:is_y())
      end)
    end)

    describe("is_z", function()
      it("should return false", function()
        assert.is_false(gate_placeholder:is_z())
      end)
    end)

    describe("is_s", function()
      it("should return false", function()
        assert.is_false(gate_placeholder:is_s())
      end)
    end)

    describe("is_t", function()
      it("should return false", function()
        assert.is_false(gate_placeholder:is_t())
      end)
    end)

    describe("is_swap", function()
      it("should return false", function()
        assert.is_false(gate_placeholder:is_swap())
      end)
    end)

    describe("is_control", function()
      it("should return false", function()
        assert.is_false(gate_placeholder:is_control())
      end)
    end)

    describe("is_cnot_x", function()
      it("should return false", function()
        assert.is_false(gate_placeholder:is_cnot_x())
      end)
    end)

    describe("is_garbage", function()
      it("should return false", function()
        assert.is_false(gate_placeholder:is_garbage())
      end)
    end)

    describe("is_placeholder", function()
      it("should return true", function()
        assert.is_true(gate_placeholder:is_placeholder())
      end)
    end)
  end)

  describe("state", function()
    it("should return 'idle'", function()
      assert.are.equals('idle', gate_placeholder.state)
    end)

    describe("is_idle", function()
      it("should return true", function()
        assert.is_true(gate_placeholder:is_idle())
      end)
    end)

    describe("is_swapping", function()
      it("should return false", function()
        assert.is_false(gate_placeholder:is_swapping())
      end)
    end)

    describe("is_swap_finished", function()
      it("should return false", function()
        assert.is_false(gate_placeholder:is_swap_finished())
      end)
    end)

    describe("is_dropping", function()
      it("should return false", function()
        assert.is_false(gate_placeholder:is_dropping())
      end)
    end)

    describe("is_dropped", function()
      it("should return false", function()
        assert.is_false(gate_placeholder:is_dropped())
      end)
    end)

    describe("is_match", function()
      it("should return false", function()
        assert.is_false(gate_placeholder:is_match())
      end)
    end)
  end)

  describe("stringify", function()
    it("should return '?'", function()
      assert.are.equals('?', stringify(gate_placeholder))
    end)
  end)
end)
