require("engine/test/bustedhelper")
local particle = require("particle")

describe('particle', function()
  describe('constructor', function()
    it("creates a particle", function()
      assert.has_no.errors(function()
        particle(1, 1, 1, 1, 1, 1)
      end)
    end)
  end)

  describe('update', function()
    it("updates all partciles", function()
      particle(1, 1, 1, 1, 1, 1)

      assert.has_no.errors(function()
        particle.update()
      end)
    end)
  end)

  describe('render', function()
    it("renders all particles", function()
      particle(1, 1, 1, 1, 1, 1)

      assert.has_no.errors(function()
        particle.render()
      end)
    end)
  end)
end)
